env:
  node: true
  commonjs: true
  es6: true
  jest/globals: true
extends:
  - standard
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins:
    - jest
rules:
    indent:
        - error
        - 4
